# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-K23-lqKtI-2OZK7OZOFZ12Lb3riWU5C
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Анализ заработной платы", layout="centered")
st.title("Анализ заработной платы по отраслям")

@st.cache_data
def load_data():
    data = pd.read_excel("nominal_wage.xlsx")
    cpi = pd.read_excel("CPI.xlsx")
    return data, cpi

data, cpi = load_data()

industries = [data['Отрасль'].loc[26], data['Отрасль'].loc[27], data['Отрасль'].loc[28]]

industry_name = st.selectbox("Выберите отрасль:", industries)

df = data[data['Отрасль'] == industry_name].T.reset_index().drop(0)
df.rename(columns={'index': 'Год', df.columns[1]: 'nominal wage'}, inplace=True)
df['Год'] = df['Год'].astype(int)

df['real wage'] = df.apply(
    lambda row: row['nominal wage'] / (
        cpi[cpi['Год'] == row['Год']]['ИПЦ'].values[0] /
        cpi[cpi['Год'] == row['Год'] - 1]['ИПЦ'].values[0]
    ),
    axis=1
)

chart_option = st.radio("Выберите график:", [
    "Номинальная ЗП",
    "Реальная ЗП",
    "Номинальная и реальная ЗП",
    "Сравнение средних"
])

fig, ax = plt.subplots(figsize=(12, 8))

if chart_option == "Номинальная ЗП":
    ax.plot(df['Год'], df['nominal wage'],
            marker='o', linestyle='-', color='royalblue', linewidth=2, markersize=6,
            label='Номинальная ЗП')
    ax.set_title(f'Динамика номинальной заработной платы\nОтрасль: {industry_name}', fontsize=16, pad=20)
    ax.set_ylabel('Заработная плата, руб.')

elif chart_option == "Реальная ЗП":
    ax.plot(df['Год'], df['real wage'],
            marker='o', linestyle='--', color='red', linewidth=2, markersize=7,
            label='Реальная ЗП (в ценах предыдущего года)')
    ax.set_title(f'Динамика реальной заработной платы\nОтрасль: {industry_name}', fontsize=16, pad=20)
    ax.set_ylabel('Заработная плата, руб.')

elif chart_option == "Номинальная и реальная ЗП":
    ax.plot(df['Год'], df['nominal wage'],
            marker='o', linestyle='-', color='royalblue', linewidth=2, markersize=6,
            label='Номинальная ЗП')
    ax.plot(df['Год'], df['real wage'],
            marker='x', linestyle='--', color='red', linewidth=2, markersize=7,
            label='Реальная ЗП (в ценах предыдущего года)')
    ax.set_title(f'Динамика номинальной и реальной заработной платы\nОтрасль: {industry_name}', fontsize=16, pad=20)
    ax.set_ylabel('Заработная плата, руб.')

elif chart_option == "Сравнение средних":
    sns.barplot(data=df[['nominal wage', 'real wage']].mean().reset_index(), x='index', y=0, ax=ax)
    ax.set_title(f'Сравнение номинальной и реальной заработной платы\nОтрасль: {industry_name}', fontsize=16, pad=20)
    ax.set_xlabel('Тип ЗП')
    ax.set_ylabel('Средняя заработная плата, руб.')

ax.set_xlabel('Год')
ax.grid(True)
ax.tick_params(axis='both', which='major', labelsize=12)
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
st.pyplot(fig)

st.markdown("---")
st.caption("Данные: nominal_wage.xlsx и CPI.xlsx")